version: 2

models:
  - name: encuestas_totales
    description: "Encuestas con datos combinados de personas, religión y frecuencias"
    columns:
      - name: id_encuesta
      - name: dni
      - name: nombre_religion


  - name: promedios_por_religion
    description: "Promedios de espiritualidad y religiosidad por religión"
    columns:
      - name: nombre_religion
      - name: promedio_espiritualidad
      - name: promedio_religiosidad
        data_test:
          - unique
          - not_null
